version: '3.9'

services:
  app:
    build:
      context: .
    image: car_showroom_manager
    command: >
      sh -c "cd car_showroom_manager &&
             python manage.py makemigrations &&
             python manage.py migrate
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./car_showroom_manager:/car_showroom_manager
      - ./data/web:/vol/web
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file: .env
