# Generated by Django 4.1.4 on 2022-12-20 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="CarShowroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "location_country",
                    django_countries.fields.CountryField(max_length=2),
                ),
                ("location_city", models.CharField(max_length=30)),
                ("locarion_street", models.CharField(max_length=30)),
                ("location_house", models.CharField(max_length=30)),
                (
                    "money",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
            options={
                "db_table": "car_showroom",
            },
        ),
        migrations.CreateModel(
            name="CarShowroomVehisle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("model", models.CharField(max_length=30)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount", models.IntegerField()),
                (
                    "car_chowroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="core.carshowroom",
                    ),
                ),
            ],
            options={
                "db_table": "car_showroom_vehicle",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=30)),
                ("date_of_foundation", models.DateField()),
                ("number_of_buyers", models.IntegerField()),
            ],
            options={
                "db_table": "provider",
            },
        ),
        migrations.CreateModel(
            name="ProviderVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("model", models.CharField(max_length=30)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount", models.IntegerField()),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="core.provider",
                    ),
                ),
            ],
            options={
                "db_table": "provider_vehicle",
            },
        ),
        migrations.CreateModel(
            name="UserPurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("amount", models.IntegerField()),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("purchase_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "car_showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_purchase_history",
                        to="core.carshowroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_purchase_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_purchase_history",
                        to="core.carshowroomvehisle",
                    ),
                ),
            ],
            options={
                "db_table": "user_purchase_history",
            },
        ),
        migrations.CreateModel(
            name="ProviderVehicleCharacteristics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("body_type", models.CharField(max_length=30)),
                ("number_of_seats", models.IntegerField()),
                ("load_capacity", models.IntegerField()),
                (
                    "weight",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "engine_type",
                    models.CharField(
                        choices=[
                            ("P", "Petrol"),
                            ("D", "Diesel"),
                            ("E", "Electricity"),
                        ],
                        max_length=1,
                    ),
                ),
                ("max_speed", models.IntegerField()),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="core.providervehicle",
                    ),
                ),
            ],
            options={
                "db_table": "provider_vehicle_characteristics",
            },
        ),
        migrations.CreateModel(
            name="ProviderSpecialOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("date_from", models.DateTimeField()),
                ("date_to", models.DateTimeField()),
                ("discount", models.IntegerField()),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_offers",
                        to="core.provider",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_offers",
                        to="core.providervehicle",
                    ),
                ),
            ],
            options={
                "db_table": "provider_special_offer",
            },
        ),
        migrations.CreateModel(
            name="ProviderPurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("amount", models.IntegerField()),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("purchase_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "car_showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_purchase_history",
                        to="core.carshowroom",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_purchase_history",
                        to="core.provider",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_purchase_history",
                        to="core.providervehicle",
                    ),
                ),
            ],
            options={
                "db_table": "provider_purchase_history",
            },
        ),
        migrations.CreateModel(
            name="ProviderDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("purchases_before_discount", models.IntegerField()),
                ("discount", models.IntegerField()),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="core.provider",
                    ),
                ),
            ],
            options={
                "db_table": "provider_discount",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("first_name", models.CharField(max_length=30)),
                ("second_name", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("driver_license", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile",
            },
        ),
        migrations.CreateModel(
            name="DesiredVehicleCharacteristics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("body_type", models.CharField(max_length=30)),
                ("number_of_seats", models.IntegerField()),
                ("load_capacity", models.IntegerField()),
                (
                    "weight",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "engine_type",
                    models.CharField(
                        choices=[
                            ("P", "Petrol"),
                            ("D", "Diesel"),
                            ("E", "Electricity"),
                        ],
                        max_length=1,
                    ),
                ),
                ("max_speed", models.IntegerField()),
                (
                    "car_showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desired_characteristics",
                        to="core.carshowroom",
                    ),
                ),
            ],
            options={
                "db_table": "desired_vehicle_characteristics",
            },
        ),
        migrations.CreateModel(
            name="CarShowroomVehicleCharacteristics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("body_type", models.CharField(max_length=30)),
                ("number_of_seats", models.IntegerField()),
                ("load_capacity", models.IntegerField()),
                (
                    "weight",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "engine_type",
                    models.CharField(
                        choices=[
                            ("P", "Petrol"),
                            ("D", "Diesel"),
                            ("E", "Electricity"),
                        ],
                        max_length=1,
                    ),
                ),
                ("max_speed", models.IntegerField()),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="core.carshowroomvehisle",
                    ),
                ),
            ],
            options={
                "db_table": "car_showroom_vehicle_characteristics",
            },
        ),
        migrations.CreateModel(
            name="CarShowroomSpecialOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("date_from", models.DateTimeField()),
                ("date_to", models.DateTimeField()),
                ("discount", models.IntegerField()),
                (
                    "car_showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_offers",
                        to="core.carshowroom",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_offers",
                        to="core.carshowroomvehisle",
                    ),
                ),
            ],
            options={
                "db_table": "car_showroom_special_offer",
            },
        ),
        migrations.CreateModel(
            name="CarShowroomProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("number_of_purchases", models.IntegerField()),
                (
                    "car_showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.carshowroom",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.provider",
                    ),
                ),
            ],
            options={
                "db_table": "car_showroom_provider",
            },
        ),
        migrations.AddField(
            model_name="carshowroom",
            name="providers",
            field=models.ManyToManyField(
                related_name="car_showrooms",
                through="core.CarShowroomProvider",
                to="core.provider",
            ),
        ),
    ]
